# Generated by Django 2.1.5 on 2019-02-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('seats', models.IntegerField()),
                ('projector', models.BooleanField(default=False)),
            ],
        ),
    ]
